[package]
name = "desperado"
version = "0.1.0"
edition = "2021"
authors = ["Wil Cram"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { git = "https://github.com/amethyst/bracket-lib" }
specs = "0.16.1"
specs-derive = "0.4.1"